### ISSUE TITLE
SIGSEGV when running vault-list-secrets --remote --detailed

### ISSUE THREAD

**Issue by danielzhanghl** [seatgeek/hashi-helper#11]
Hi, when tries it, a Sevg happened as below, maybe some fix need to make that be more reliable.
thanks,

```
$  ./hashi-helper  vault-list-secrets --remote --detailed
INFO[0000] value = http://localhost:8181                 app=api-admin env=production secret=API_URL
INFO[0000]
panic: runtime error: invalid memory address or nil pointer dereference
**[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ca144]**

goroutine 1 [running]:
github.com/seatgeek/hashi-helper/command/vault.secretListLocal(0xc4200c4b40, 0x8b3601, 0x6)
        **/Users/go_src/src/github.com/seatgeek/hashi-helper/command/vault/secrets_list.go:29 +0x184**
github.com/seatgeek/hashi-helper/command/vault.SecretsList(0xc4200c4b40, 0xc420049320, 0x778241)
        /Users/go_src/src/github.com/seatgeek/hashi-helper/command/vault/secrets_list.go:17 +0x87
main.main.func5(0xc4200c4b40, 0x100, 0xc4200c4b40)
        /Users/go_src/src/github.com/seatgeek/hashi-helper/main.go:101 +0x2b
gopkg.in/urfave/cli%2ev1.HandleAction(0x823ea0, 0x8cb2a8, 0xc4200c4b40, 0xc42005e700, 0x0)
        /Users/go_src/src/gopkg.in/urfave/cli.v1/app.go:485 +0xd4
gopkg.in/urfave/cli%2ev1.Command.Run(0x8b8623, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8c2d0a, 0x27, 0x0, ...)
        /Users/go_src/src/gopkg.in/urfave/cli.v1/command.go:193 +0xb72
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200d89c0, 0xc4200101c0, 0x4, 0x4, 0x0, 0x0)
        /Users/go_src/src/gopkg.in/urfave/cli.v1/app.go:250 +0x7d0
main.main()
        /Users/go_src/src/github.com/seatgeek/hashi-helper/main.go:255 +0x12d5
```

**Comment by jippi** [comment]
Do you use a root token or what is the permissions you try to list secrets with? Need more information to be able to debug it :)

**Comment by danielzhanghl** [comment]
i use a root token, seem like there is some k/v i wrote that before didn't use this tool, therefore there is no env/app attribute, cause this issue?
